site_name: dotdrop
site_url: https://github.com/deadc0de6/dotdrop
repo_url: https://github.com/deadc0de6/dotdrop
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
      - yaml
    collapse_navigation: false
use_directory_urls: true
nav:
  - Home: 'README.md'
  - Installation: 'installation.md'
  - Usage: 'usage.md'
  - Config: 'config.md'
  - Templating: 'templating.md'
  - HowTo: 'howto/README.md'
  - Contributing: 'contributing.md'
markdown_extensions:
  - meta
  - tables
  - fenced_code
  - toc

