site_name: dotdrop
site_url: https://github.com/deadc0de6/dotdrop
repo_url: https://github.com/deadc0de6/dotdrop
theme:
    name: readthedocs
    highlightjs: true
use_directory_urls: true
nav:
  - Home: 'README.md'
  - Installation: 'installation.md'
  - Usage: 'usage.md'
  - Config: 'config/config.md'
  - Template: 'template/templating.md'
  - HowTo: 'howto/README.md'
  - Contributing: 'contributing.md'
markdown_extensions:
    - toc:
        baselevel: 2
        permalink: "#"

