site_name: dotdrop
site_url: https://github.com/deadc0de6/dotdrop
repo_url: https://github.com/deadc0de6/dotdrop
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
      - yaml
    collapse_navigation: false
use_directory_urls: true
nav:
  - 'Dotdrop': 'README.md'
  - 'Installation': 'installation.md'
  - 'Getting started': 'getting-started.md'
  - 'Usage': 'usage.md'
  - 'Config':
    - 'Config file': 'config-file.md'
    - 'Config block': 'config-config.md'
    - 'Dotfiles block': 'config-dotfiles.md'
    - 'Profiles block': 'config-profiles.md'
    - 'Actions block': 'config-actions.md'
    - 'Transformations block': 'config-transformations.md'
    - 'Variables block': 'config-variables.md'
    - 'Dynvariables block': 'config-dynvars.md'
    - 'Uservariables block': 'config-uservars.md'
  - 'Templating':
    - 'Templating': 'templating.md'
  - 'More':
    - 'HowTo': 'howto/howto.md'
markdown_extensions:
  - meta
  - tables
  - fenced_code
  - toc:
      permalink: True
extra_css:
    - css/extra.css

